\c midterm;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS cart CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS menu CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;

CREATE TABLE customer (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  phone_number VARCHAR(15)
);

CREATE TABLE cart (
  id SERIAL PRIMARY KEY NOT NULL,
  customer_id INTEGER REFERENCES customer(id) ON DELETE CASCADE
);

CREATE TABLE menu (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  price MONEY
);

CREATE TABLE cart_items (
  id SERIAL PRIMARY KEY NOT NULL,
  cart_id INTEGER REFERENCES cart(id) ON DELETE CASCADE,
  menu_id INTEGER REFERENCES menu(id) ON DELETE CASCADE,
  price MONEY
);